import test from 'node:test';
import assert from 'node:assert/strict';
import {AniSubRuntime} from '../../core/src/runtime.mjs';
import {VirtualScheduler,FakeTranslator,FakeTts} from '../../providers/fake/src/index.mjs';
function setup(options={}){const scheduler=new VirtualScheduler();const events=[];const runtime=new AniSubRuntime({scheduler,translator:new FakeTranslator({scheduler,...options.translation}),tts:new FakeTts({scheduler,...options.tts}),onEvent:e=>events.push(e)});let seq=0,revision=0,id='s';const send=(type,body={})=>runtime.handle({type,sessionId:id,seq:++seq,revision,...body});const open=(newId='s')=>{id=newId;seq=0;revision=0;return send('OPEN',{descriptor:{inputMode:'DIRECT',translation:true,speech:true},clock:{positionMediaMs:0,playing:true,speed:1}});};const control=(event,pos=0)=>{if(event!=='PLAY')revision++;return send('PLAYBACK',{event,positionMediaMs:pos});};open();return {runtime,scheduler,events,send,open,control};}
const cue=(cueId='c',extra={})=>({cueId,originalText:'synthetic',origin:'DIRECT',observedAtMediaMs:0,...extra});
const speech=(x,event)=>x.events.filter(e=>e.type==='SPEECH'&&e.event===event);
test('normal translated cue and virtual exactly-once speech with independent counters',async()=>{const x=setup();x.send('SNAPSHOT',{cues:[cue()]});await x.scheduler.advance(40);assert.equal(x.events[0].type,'CUE');assert.equal(x.events[0].cue.originalText,'synthetic');assert.equal(x.events[0].cue.startMediaMs,undefined);assert.equal(speech(x,'STARTED').length,1);await x.scheduler.advance(300);assert.equal(speech(x,'FINISHED').length,1);assert.equal(speech(x,'FINISHED')[0].finishReason,'COMPLETED');assert.deepEqual(x.events.map(e=>e.seq),[1,2,3]);assert.equal(x.runtime.diagnostics().outstandingJobs,0);});
test('pause stops output immediately; terminal keeps accepted old revision and never replays',async()=>{const x=setup();x.send('SNAPSHOT',{cues:[cue()]});await x.scheduler.advance(40);x.control('PAUSE',40);assert.equal(speech(x,'FINISHED').length,1);assert.equal(speech(x,'FINISHED')[0].revision,0);assert.equal(x.runtime.diagnostics().revision,1);x.control('PLAY',40);await x.scheduler.advance(1000);assert.equal(speech(x,'STARTED').length,1);assert.equal(speech(x,'FINISHED').length,1);});
test('seek retires uncooperative completion, no stale cue or STARTED',async()=>{const x=setup({translation:{latencyMs:100,ignoreCancel:true}});x.send('SNAPSHOT',{cues:[cue()]});x.control('SEEK',2000);await x.scheduler.advance(200);assert.equal(x.events.length,0);assert.equal(x.runtime.diagnostics().stale,1);});
test('stale TTS after pause rejected even if translation already emitted',async()=>{const x=setup({tts:{latencyMs:100,ignoreCancel:true}});x.send('SNAPSHOT',{cues:[cue()]});await x.scheduler.advance(20);x.control('PAUSE',20);await x.scheduler.advance(200);assert.equal(speech(x,'STARTED').length,0);assert.equal(x.runtime.diagnostics().outstandingJobs,0);});
test('known future start waits media clock; expired inference drops',async()=>{const x=setup();x.send('SNAPSHOT',{cues:[cue('future',{startMediaMs:500,endMediaMs:1000})]});await x.scheduler.advance(499);assert.equal(speech(x,'STARTED').length,0);await x.scheduler.advance(1);assert.equal(speech(x,'STARTED').length,1);const y=setup({translation:{latencyMs:100}});y.send('SNAPSHOT',{cues:[cue('old',{endMediaMs:50})]});await y.scheduler.advance(100);assert.equal(y.events.length,0);assert.equal(y.runtime.diagnostics().expired,1);});
test('empty snapshot clears active output and cancels work without fallback',async()=>{const x=setup();x.send('SNAPSHOT',{cues:[cue()]});await x.scheduler.advance(40);x.send('SNAPSHOT',{cues:[]});assert.equal(x.runtime.diagnostics().activeCues,0);assert.equal(speech(x,'FINISHED').length,1);await x.scheduler.advance(1000);assert.equal(speech(x,'STARTED').length,1);});
test('outstanding cap includes uncooperative jobs retired by seek',async()=>{const x=setup({translation:{latencyMs:100,ignoreCancel:true}});x.send('SNAPSHOT',{cues:Array.from({length:8},(_,i)=>cue(`a${i}`))});x.control('SEEK');x.send('SNAPSHOT',{cues:[cue('new')]});assert.equal(x.runtime.diagnostics().outstandingJobs,8);assert.equal(x.runtime.diagnostics().backpressure,1);await x.scheduler.advance(200);assert.equal(x.runtime.diagnostics().outstandingJobs,0);});
test('waiting segments bounded and distant media horizon denied',async()=>{const x=setup();x.send('SNAPSHOT',{cues:Array.from({length:8},(_,i)=>cue(`a${i}`,{startMediaMs:1000,endMediaMs:2000}))});await x.scheduler.advance(40);assert.equal(x.runtime.diagnostics().waitingSpeech,2);assert.equal(x.runtime.diagnostics().backpressure,6);const y=setup();y.send('SNAPSHOT',{cues:[cue('distant',{startMediaMs:10000})]});await y.scheduler.advance(40);assert.equal(y.runtime.diagnostics().waitingSpeech,0);assert.equal(y.runtime.diagnostics().backpressure,1);});
test('validation/revision/order failures do not mutate state; duplicate seq ignored',()=>{const x=setup();const before=x.runtime.diagnostics();assert.equal(x.runtime.handle({type:'PLAYBACK',sessionId:'s',seq:2,revision:0,event:'SEEK',positionMediaMs:100}).accepted,false);assert.equal(x.runtime.diagnostics().revision,before.revision);assert.equal(x.runtime.handle({type:'SNAPSHOT',sessionId:'s',seq:2,revision:0,cues:[cue()]}).accepted,true);assert.equal(x.runtime.handle({type:'SNAPSHOT',sessionId:'s',seq:2,revision:0,cues:[]}).accepted,true);assert.equal(x.runtime.diagnostics().activeCues,1);assert.equal(x.runtime.handle({type:'SNAPSHOT',sessionId:'s',seq:1,revision:0,cues:[]}).accepted,false);});
test('source replacement closes, new session counters reset; old ids cannot reopen',async()=>{const x=setup();x.send('SNAPSHOT',{cues:[cue()]});await x.scheduler.advance(40);x.control('SOURCE_CHANGE',0);assert.equal(x.runtime.diagnostics().sessionOpen,false);assert.equal(x.open('s2').accepted,true);x.send('SNAPSHOT',{cues:[cue()]});await x.scheduler.advance(40);assert.equal(x.events.find(e=>e.sessionId==='s2').seq,1);x.runtime.disconnect();assert.equal(x.open('s').accepted,false);await x.scheduler.advance(1000);assert.equal(speech(x,'FINISHED').length,2);assert.equal(x.scheduler.pending(),0);});
test('provider failure sanitized, disconnect cancels cooperative pending task',async()=>{const x=setup({translation:{fail:true}});x.send('SNAPSHOT',{cues:[cue()]});await x.scheduler.advance(20);assert.equal(x.events[0].code,'PROVIDER_FAILED');assert.equal(JSON.stringify(x.runtime.diagnostics()).includes('synthetic'),false);const y=setup();y.send('SNAPSHOT',{cues:[cue()]});y.runtime.disconnect();await y.scheduler.advance(100);assert.equal(y.runtime.diagnostics().outstandingJobs,0);assert.equal(y.scheduler.pending(),0);});
test('speed, stop, input-track invalidation prevent stale completion',async()=>{for(const mode of ['PLAYBACK_SPEED','STOP','INPUT_CHANGED']){const x=setup({translation:{ignoreCancel:true}});x.send('SNAPSHOT',{cues:[cue()]});if(mode==='INPUT_CHANGED')x.runtime.handle({type:mode,sessionId:'s',seq:3,revision:1,cues:[]});else x.control(mode);await x.scheduler.advance(100);assert.equal(speech(x,'STARTED').length,0);assert.equal(x.events.filter(e=>e.type==='CUE').length,0);}});
