package com.anisub.runtime.protocol;

public enum RuntimeError {
    PROTOCOL_MISMATCH, UNAUTHORIZED, MALFORMED, UNSUPPORTED, UNSUPPORTED_TRANSLATION,
    UNAVAILABLE, MODEL_MISSING, MODEL_CORRUPT, MODEL_INCOMPATIBLE, MODEL_IN_USE,
    SETTINGS_CONFLICT, STALE, CLOCK_STALE, EXPIRED, OUTSIDE_HORIZON, BACKPRESSURE,
    PROVIDER_FAILED, TIMEOUT, DISCONNECTED, CANCELLED
}
